### PR TITLE
update

### PR DESCRIPTION
**Pull request by JeffDeCola**

### CODE REVIEW

**Comment by jaytberry77** [comment]
Hello Jeff I attempted to install your Zcash miner but I don’t think I succeeded. I got pretty far along then ran into errors after adding the keys

**Comment by JeffDeCola** [comment]
Are you doing a full node or using a pool?  I suggest doing a pool (you can still do a private pool), since a full node is such a pain.

**Comment by jaytberry77** [comment]
I’m kinda lost I don’t think I’m gonna do either I deposited 200$ into my IFWallet/ViaWallet account only for it to disappear, I was gonna use that as a starting point to buy some power, so not really trusting my abilities in proper coding and script editing and really not trusting IF/ViaWallet at the moment!!

**Comment by JeffDeCola** [comment]
I don't know what IFWallet/ViaWallet account is.  If it's a wallet, someone did the xfer and you can see it.

And yes, it can be confusing.  There are exchanges, there are wallets that keep your private key, there are wallets you keep (with your private key), etc...

If you mine coins I suggest transferring all you "minted" coins to something trusted like coinbase (an exchange with wallets they keep for you) or coinbase wallet (your wallet, but they keep your private keys).  This is what I do.

Just note, most people never mine for coins, they just buy/sell crypto on the exchanges like coinbase and never care about wallets.

Mining is a pretty big learning curve.  I suggest starting with a pool like 2miners. It's just so much easier.  And you really need a pretty good graphic card. At least a 1080.

**Pull request merged**
